import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";
import Providers from "./providers";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} bg-mainbackground font-pretendard antialiased`}
      >
        <Providers>
          <main className="container mx-auto h-dvh w-full px-6">
            {children}
          </main>
        </Providers>
        <script defer src="/service-worker.js" />
      </body>
    </html>
  );
}
